"""empty message

Revision ID: 25c847a6b0de
Revises: 666c8750a349
Create Date: 2023-07-21 09:52:39.118388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c847a6b0de'
down_revision = '666c8750a349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiln', schema=None) as batch_op:
        batch_op.alter_column('controller',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiln', schema=None) as batch_op:
        batch_op.alter_column('controller',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)

    # ### end Alembic commands ###
