"""empty message

Revision ID: 2cf08375b536
Revises: 7dd7ebb81041
Create Date: 2023-09-05 11:45:22.264741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf08375b536'
down_revision = '7dd7ebb81041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_segment',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('segment_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['firing_program.id'], name=op.f('fk_program_segment_program_id_firing_program')),
    sa.ForeignKeyConstraint(['segment_id'], ['firing_segment.id'], name=op.f('fk_program_segment_segment_id_firing_segment')),
    sa.PrimaryKeyConstraint('program_id', 'segment_id', name=op.f('pk_program_segment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_segment')
    # ### end Alembic commands ###
