"""empty message

Revision ID: 37d6092d8732
Revises: 2cf08375b536
Create Date: 2023-09-06 00:59:35.691584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d6092d8732'
down_revision = '2cf08375b536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clay', schema=None) as batch_op:
        batch_op.drop_column('grog_size_unit')
        batch_op.drop_column('temp_unit')

    with op.batch_alter_table('firing_segment', schema=None) as batch_op:
        batch_op.drop_column('temp_unit')
        batch_op.drop_column('time_to_reach_unit')

    with op.batch_alter_table('kiln', schema=None) as batch_op:
        batch_op.drop_column('capacity_unit')
        batch_op.drop_column('temp_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiln', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_unit', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('capacity_unit', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('firing_segment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_to_reach_unit', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('temp_unit', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('clay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_unit', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('grog_size_unit', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
