"""empty message

Revision ID: 60bb81c11639
Revises: 9a725acac2ec
Create Date: 2023-06-30 14:23:14.154048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bb81c11639'
down_revision = '9a725acac2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_segment',
    sa.Column('firing_program_id', sa.Integer(), nullable=True),
    sa.Column('firing_segment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firing_program_id'], ['firing_program.id'], name=op.f('fk_program_segment_firing_program_id_firing_program')),
    sa.ForeignKeyConstraint(['firing_segment_id'], ['firing_segment.id'], name=op.f('fk_program_segment_firing_segment_id_firing_segment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_segment')
    # ### end Alembic commands ###
