"""empty message

Revision ID: 666c8750a349
Revises: 60bb81c11639
Create Date: 2023-06-30 14:29:40.735206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666c8750a349'
down_revision = '60bb81c11639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pot_glaze',
    sa.Column('pot_id', sa.Integer(), nullable=True),
    sa.Column('glaze_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['glaze_id'], ['glaze.id'], name=op.f('fk_pot_glaze_glaze_id_glaze')),
    sa.ForeignKeyConstraint(['pot_id'], ['pot.id'], name=op.f('fk_pot_glaze_pot_id_pot'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pot_glaze')
    # ### end Alembic commands ###
