"""empty message

Revision ID: 7f8b831a5c72
Revises: 37d6092d8732
Create Date: 2023-09-08 23:28:48.072813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8b831a5c72'
down_revision = '37d6092d8732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glaze', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cone', sa.String(length=5), nullable=True))
        batch_op.drop_column('temp_unit')

    with op.batch_alter_table('kiln', schema=None) as batch_op:
        batch_op.alter_column('voltage',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Float(precision=20),
               existing_nullable=True)

    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.drop_column('throw_dimensions_unit')
        batch_op.drop_column('throw_weight_unit')
        batch_op.drop_column('trim_weight_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trim_weight_unit', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('throw_weight_unit', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('throw_dimensions_unit', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('kiln', schema=None) as batch_op:
        batch_op.alter_column('voltage',
               existing_type=sa.Float(precision=20),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('glaze', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_unit', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('cone')

    # ### end Alembic commands ###
