"""empty message

Revision ID: 8b285b54af90
Revises: 1fde3fdc1c2b
Create Date: 2023-10-12 23:14:26.190319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b285b54af90'
down_revision = '1fde3fdc1c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_pot_glaze')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_pot_glaze',
    sa.Column('pot_id', sa.INTEGER(), nullable=True),
    sa.Column('glaze_id', sa.INTEGER(), nullable=True),
    sa.Column('number_of_layers', sa.INTEGER(), nullable=True),
    sa.Column('display_order', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['glaze_id'], ['glaze.id'], name='fk_pot_glaze_glaze_id_glaze'),
    sa.ForeignKeyConstraint(['pot_id'], ['pot.id'], name='fk_pot_glaze_pot_id_pot')
    )
    # ### end Alembic commands ###
