"""empty message

Revision ID: a392249cc3e6
Revises: e90df647d82c
Create Date: 2023-07-22 13:37:36.733866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a392249cc3e6'
down_revision = 'e90df647d82c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glaze', schema=None) as batch_op:
        batch_op.add_column(sa.Column('glaze_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glaze', schema=None) as batch_op:
        batch_op.drop_column('glaze_url')

    # ### end Alembic commands ###
