"""empty message

Revision ID: b0ae5dd569a4
Revises: 8d2033c9823b
Create Date: 2023-06-30 14:12:20.418126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ae5dd569a4'
down_revision = '8d2033c9823b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bisque_fire_kiln_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('glaze_fire_kiln_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_pot_bisque_fire_kiln')
        batch_op.drop_index('ix_pot_glaze_fire_kiln')
        batch_op.create_index(batch_op.f('ix_pot_bisque_fire_kiln_id'), ['bisque_fire_kiln_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pot_glaze_fire_kiln_id'), ['glaze_fire_kiln_id'], unique=False)
        batch_op.drop_constraint('fk_pot_glaze_fire_kiln_kiln', type_='foreignkey')
        batch_op.drop_constraint('fk_pot_bisque_fire_kiln_kiln', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pot_glaze_fire_kiln_id_kiln'), 'kiln', ['glaze_fire_kiln_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_pot_bisque_fire_kiln_id_kiln'), 'kiln', ['bisque_fire_kiln_id'], ['id'])
        batch_op.drop_column('glaze_fire_kiln')
        batch_op.drop_column('bisque_fire_kiln')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bisque_fire_kiln', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('glaze_fire_kiln', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_pot_bisque_fire_kiln_id_kiln'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_pot_glaze_fire_kiln_id_kiln'), type_='foreignkey')
        batch_op.create_foreign_key('fk_pot_bisque_fire_kiln_kiln', 'kiln', ['bisque_fire_kiln'], ['id'])
        batch_op.create_foreign_key('fk_pot_glaze_fire_kiln_kiln', 'kiln', ['glaze_fire_kiln'], ['id'])
        batch_op.drop_index(batch_op.f('ix_pot_glaze_fire_kiln_id'))
        batch_op.drop_index(batch_op.f('ix_pot_bisque_fire_kiln_id'))
        batch_op.create_index('ix_pot_glaze_fire_kiln', ['glaze_fire_kiln'], unique=False)
        batch_op.create_index('ix_pot_bisque_fire_kiln', ['bisque_fire_kiln'], unique=False)
        batch_op.drop_column('glaze_fire_kiln_id')
        batch_op.drop_column('bisque_fire_kiln_id')

    # ### end Alembic commands ###
