"""empty message

Revision ID: cd116787ee1e
Revises: 2fc9c2c63ade
Create Date: 2023-10-25 22:08:12.970750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd116787ee1e'
down_revision = '2fc9c2c63ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission', schema=None) as batch_op:
        batch_op.drop_column('done')

    # ### end Alembic commands ###
