"""empty message

Revision ID: f4e92c0191b6
Revises: b6f9ee45445a
Create Date: 2023-08-23 20:11:53.512548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e92c0191b6'
down_revision = 'b6f9ee45445a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot_glaze', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot_glaze', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
