"""empty message

Revision ID: 0092e40997bf
Revises: 8050d3a8947c
Create Date: 2023-06-30 12:19:14.701533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0092e40997bf'
down_revision = '8050d3a8947c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pot_glaze')
    op.drop_table('program_segment')
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.drop_index('ix_pot_bisque_fire_kiln_id')
        batch_op.drop_index('ix_pot_bisque_fire_program_id')
        batch_op.drop_index('ix_pot_glaze_fire_kiln_id')
        batch_op.drop_index('ix_pot_glaze_fire_program_id')
        batch_op.drop_constraint('fk_pot_bisque_fire_program_id_firing_program', type_='foreignkey')
        batch_op.drop_constraint('fk_pot_glaze_fire_kiln_id_kiln', type_='foreignkey')
        batch_op.drop_constraint('fk_pot_bisque_fire_kiln_id_kiln', type_='foreignkey')
        batch_op.drop_constraint('fk_pot_glaze_fire_program_id_firing_program', type_='foreignkey')
        batch_op.drop_column('glaze_fire_program_id')
        batch_op.drop_column('bisque_fire_kiln_id')
        batch_op.drop_column('glaze_fire_kiln_id')
        batch_op.drop_column('bisque_fire_program_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bisque_fire_program_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('glaze_fire_kiln_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('bisque_fire_kiln_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('glaze_fire_program_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_pot_glaze_fire_program_id_firing_program', 'firing_program', ['glaze_fire_program_id'], ['id'])
        batch_op.create_foreign_key('fk_pot_bisque_fire_kiln_id_kiln', 'kiln', ['bisque_fire_kiln_id'], ['id'])
        batch_op.create_foreign_key('fk_pot_glaze_fire_kiln_id_kiln', 'kiln', ['glaze_fire_kiln_id'], ['id'])
        batch_op.create_foreign_key('fk_pot_bisque_fire_program_id_firing_program', 'firing_program', ['bisque_fire_program_id'], ['id'])
        batch_op.create_index('ix_pot_glaze_fire_program_id', ['glaze_fire_program_id'], unique=False)
        batch_op.create_index('ix_pot_glaze_fire_kiln_id', ['glaze_fire_kiln_id'], unique=False)
        batch_op.create_index('ix_pot_bisque_fire_program_id', ['bisque_fire_program_id'], unique=False)
        batch_op.create_index('ix_pot_bisque_fire_kiln_id', ['bisque_fire_kiln_id'], unique=False)

    op.create_table('program_segment',
    sa.Column('firing_program_id', sa.INTEGER(), nullable=True),
    sa.Column('firing_segment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['firing_program_id'], ['firing_program.id'], name='fk_program_segment_firing_program_id_firing_program'),
    sa.ForeignKeyConstraint(['firing_segment_id'], ['firing_segment.id'], name='fk_program_segment_firing_segment_id_firing_segment')
    )
    op.create_table('pot_glaze',
    sa.Column('pot_id', sa.INTEGER(), nullable=True),
    sa.Column('glaze_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['glaze_id'], ['glaze.id'], name='fk_pot_glaze_glaze_id_glaze'),
    sa.ForeignKeyConstraint(['pot_id'], ['pot.id'], name='fk_pot_glaze_pot_id_pot')
    )
    # ### end Alembic commands ###
