"""empty message

Revision ID: 085469d24080
Revises: 8b285b54af90
Create Date: 2023-10-12 23:30:49.542227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085469d24080'
down_revision = '8b285b54af90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pot_glaze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pot_id', sa.Integer(), nullable=True),
    sa.Column('glaze_id', sa.Integer(), nullable=True),
    sa.Column('number_of_layers', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['glaze_id'], ['glaze.id'], name=op.f('fk_pot_glaze_glaze_id_glaze')),
    sa.ForeignKeyConstraint(['pot_id'], ['pot.id'], name=op.f('fk_pot_glaze_pot_id_pot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pot_glaze'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pot_glaze')
    # ### end Alembic commands ###
