"""empty message

Revision ID: 0956971d4a6d
Revises: 30c4ca866a85
Create Date: 2024-01-19 14:47:26.285860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0956971d4a6d'
down_revision = '30c4ca866a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glaze', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.drop_index('ix_pot_throw_weight')
        batch_op.drop_index('ix_pot_trim_weight')
        batch_op.drop_column('trim_weight')
        batch_op.drop_column('throw_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('throw_weight', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('trim_weight', sa.INTEGER(), nullable=True))
        batch_op.create_index('ix_pot_trim_weight', ['trim_weight'], unique=False)
        batch_op.create_index('ix_pot_throw_weight', ['throw_weight'], unique=False)

    with op.batch_alter_table('glaze', schema=None) as batch_op:
        batch_op.alter_column('brand_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
