"""empty message

Revision ID: 16335c139155
Revises: 7624d81defce
Create Date: 2023-09-15 14:57:59.023439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16335c139155'
down_revision = '7624d81defce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_id', sa.String(length=140), nullable=True))
        batch_op.create_index(batch_op.f('ix_clay_name_id'), ['name_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clay', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clay_name_id'))
        batch_op.drop_column('name_id')

    # ### end Alembic commands ###
