"""empty message

Revision ID: 1fde3fdc1c2b
Revises: 95a1677c1a2f
Create Date: 2023-09-30 03:38:11.336038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fde3fdc1c2b'
down_revision = '95a1677c1a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiln', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('controller_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiln', schema=None) as batch_op:
        batch_op.drop_column('controller_url')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
