"""empty message

Revision ID: 220d38fbac34
Revises: 54ee1d3369f6
Create Date: 2023-08-13 17:34:11.493983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220d38fbac34'
down_revision = '54ee1d3369f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.drop_column('primary_image')

    # ### end Alembic commands ###
