"""empty message

Revision ID: 30c4ca866a85
Revises: cd116787ee1e
Create Date: 2023-10-31 13:37:48.359435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c4ca866a85'
down_revision = 'cd116787ee1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_pot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commission_id', sa.Integer(), nullable=True),
    sa.Column('pot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commission_id'], ['pot.id'], name=op.f('fk_commission_pot_commission_id_pot')),
    sa.ForeignKeyConstraint(['pot_id'], ['commission.id'], name=op.f('fk_commission_pot_pot_id_commission')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_pot'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commission_pot')
    # ### end Alembic commands ###
