"""empty message

Revision ID: 379be3e36579
Revises: 0092e40997bf
Create Date: 2023-06-30 13:15:35.452395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379be3e36579'
down_revision = '0092e40997bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bisque_fire_kiln_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pot_bisque_fire_kiln_id'), ['bisque_fire_kiln_id'], unique=True)
        batch_op.create_foreign_key(batch_op.f('fk_pot_bisque_fire_kiln_id_kiln'), 'kiln', ['bisque_fire_kiln_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pot_bisque_fire_kiln_id_kiln'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pot_bisque_fire_kiln_id'))
        batch_op.drop_column('bisque_fire_kiln_id')

    # ### end Alembic commands ###
