"""empty message

Revision ID: 3d0bb2209f6a
Revises: 0956971d4a6d
Create Date: 2024-01-31 18:13:41.947489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0bb2209f6a'
down_revision = '0956971d4a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glaze', schema=None) as batch_op:
        batch_op.drop_constraint('uq_glaze_brand_id', type_='unique')
        batch_op.drop_constraint('uq_glaze_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glaze', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_glaze_name', ['name'])
        batch_op.create_unique_constraint('uq_glaze_brand_id', ['brand_id'])

    # ### end Alembic commands ###
