"""empty message

Revision ID: 7624d81defce
Revises: 7f8b831a5c72
Create Date: 2023-09-12 21:50:32.772588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7624d81defce'
down_revision = '7f8b831a5c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glaze', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_glaze_brand_id'), ['brand_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_glaze_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('glaze', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_glaze_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_glaze_brand_id'), type_='unique')

    # ### end Alembic commands ###
