"""empty message

Revision ID: 8d2033c9823b
Revises: 3f820a625ccb
Create Date: 2023-06-30 13:46:54.476251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2033c9823b'
down_revision = '3f820a625ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('glaze_fire_kiln', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pot_glaze_fire_kiln'), ['glaze_fire_kiln'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_pot_glaze_fire_kiln_kiln'), 'kiln', ['glaze_fire_kiln'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pot_glaze_fire_kiln_kiln'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pot_glaze_fire_kiln'))
        batch_op.drop_column('glaze_fire_kiln')

    # ### end Alembic commands ###
