"""empty message

Revision ID: 96b79d4a4e20
Revises: c4938fb30826
Create Date: 2023-06-30 13:35:37.730274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b79d4a4e20'
down_revision = 'c4938fb30826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.drop_index('ix_pot_clay_type')
        batch_op.create_index(batch_op.f('ix_pot_clay_type'), ['clay_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pot_clay_type'))
        batch_op.create_index('ix_pot_clay_type', ['clay_type'], unique=False)

    # ### end Alembic commands ###
