"""empty message

Revision ID: 9c9c9ebffa9e
Revises: f4e92c0191b6
Create Date: 2023-08-27 11:32:29.491705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9c9ebffa9e'
down_revision = 'f4e92c0191b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('made_with_clay', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_pot_clay_type')
        batch_op.create_index(batch_op.f('ix_pot_made_with_clay'), ['made_with_clay'], unique=False)
        batch_op.drop_constraint('fk_pot_clay_type_clay', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pot_made_with_clay_clay'), 'clay', ['made_with_clay'], ['id'])
        batch_op.drop_column('clay_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clay_type', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_pot_made_with_clay_clay'), type_='foreignkey')
        batch_op.create_foreign_key('fk_pot_clay_type_clay', 'clay', ['clay_type'], ['id'])
        batch_op.drop_index(batch_op.f('ix_pot_made_with_clay'))
        batch_op.create_index('ix_pot_clay_type', ['clay_type'], unique=False)
        batch_op.drop_column('made_with_clay')

    # ### end Alembic commands ###
