"""DB created with all the tables and the naming convention added to __init__.py

Revision ID: a898e7103c93
Revises: 
Create Date: 2023-06-16 10:17:59.954669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a898e7103c93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=140), nullable=True),
    sa.Column('color', sa.String(length=140), nullable=True),
    sa.Column('temp_min', sa.Integer(), nullable=True),
    sa.Column('temp_max', sa.Integer(), nullable=True),
    sa.Column('temp_unit', sa.String(length=10), nullable=True),
    sa.Column('grog_percent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clay'))
    )
    with op.batch_alter_table('clay', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clay_brand'), ['brand'], unique=False)

    op.create_table('firing_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firing_program'))
    )
    op.create_table('firing_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp_start', sa.Integer(), nullable=True),
    sa.Column('temp_end', sa.Integer(), nullable=True),
    sa.Column('temp_unit', sa.String(length=10), nullable=True),
    sa.Column('time_to_reach', sa.Integer(), nullable=True),
    sa.Column('time_to_reach_unit', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_firing_segment'))
    )
    op.create_table('glaze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=140), nullable=True),
    sa.Column('color', sa.String(length=140), nullable=True),
    sa.Column('temp_min', sa.Integer(), nullable=True),
    sa.Column('temp_max', sa.Integer(), nullable=True),
    sa.Column('temp_unit', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glaze'))
    )
    with op.batch_alter_table('glaze', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glaze_brand'), ['brand'], unique=False)

    op.create_table('kiln',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('brand', sa.String(length=140), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('capacity_unit', sa.String(length=10), nullable=True),
    sa.Column('temp_max', sa.Integer(), nullable=True),
    sa.Column('temp_unit', sa.String(length=10), nullable=True),
    sa.Column('voltage', sa.String(length=20), nullable=True),
    sa.Column('controller', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kiln'))
    )
    with op.batch_alter_table('kiln', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiln_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_kiln_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('pot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vessel_type', sa.String(length=50), nullable=True),
    sa.Column('clay_type', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=30), nullable=True),
    sa.Column('throw_date', sa.DateTime(), nullable=True),
    sa.Column('throw_weight', sa.Integer(), nullable=True),
    sa.Column('throw_weight_unit', sa.String(length=10), nullable=True),
    sa.Column('throw_height', sa.String(length=140), nullable=True),
    sa.Column('throw_width', sa.String(length=140), nullable=True),
    sa.Column('throw_dimensions_unit', sa.String(length=10), nullable=True),
    sa.Column('throw_notes', sa.Text(), nullable=True),
    sa.Column('trim_date', sa.DateTime(), nullable=True),
    sa.Column('trim_weight', sa.Integer(), nullable=True),
    sa.Column('trim_weight_unit', sa.String(length=10), nullable=True),
    sa.Column('trim_surface_treatment', sa.String(length=140), nullable=True),
    sa.Column('trim_notes', sa.Text(), nullable=True),
    sa.Column('bisque_fire_start', sa.DateTime(), nullable=True),
    sa.Column('bisque_fire_program_id', sa.Integer(), nullable=True),
    sa.Column('bisque_fire_kiln', sa.Integer(), nullable=True),
    sa.Column('bisque_fire_end', sa.DateTime(), nullable=True),
    sa.Column('bisque_fire_open', sa.DateTime(), nullable=True),
    sa.Column('bisque_fire_notes', sa.Text(), nullable=True),
    sa.Column('glaze_date', sa.DateTime(), nullable=True),
    sa.Column('glaze_notes', sa.Text(), nullable=True),
    sa.Column('glaze_fire_start', sa.DateTime(), nullable=True),
    sa.Column('glaze_fire_program_id', sa.Integer(), nullable=True),
    sa.Column('glaze_fire_kiln', sa.Integer(), nullable=True),
    sa.Column('glaze_fire_end', sa.DateTime(), nullable=True),
    sa.Column('glaze_fire_open', sa.DateTime(), nullable=True),
    sa.Column('glaze_fire_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bisque_fire_kiln'], ['kiln.id'], name=op.f('fk_pot_bisque_fire_kiln_kiln')),
    sa.ForeignKeyConstraint(['bisque_fire_program_id'], ['firing_program.id'], name=op.f('fk_pot_bisque_fire_program_id_firing_program')),
    sa.ForeignKeyConstraint(['clay_type'], ['clay.id'], name=op.f('fk_pot_clay_type_clay')),
    sa.ForeignKeyConstraint(['glaze_fire_kiln'], ['kiln.id'], name=op.f('fk_pot_glaze_fire_kiln_kiln')),
    sa.ForeignKeyConstraint(['glaze_fire_program_id'], ['firing_program.id'], name=op.f('fk_pot_glaze_fire_program_id_firing_program')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pot'))
    )
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pot_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_pot_bisque_fire_kiln'), ['bisque_fire_kiln'], unique=True)
        batch_op.create_index(batch_op.f('ix_pot_bisque_fire_program_id'), ['bisque_fire_program_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pot_bisque_fire_start'), ['bisque_fire_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_pot_clay_type'), ['clay_type'], unique=True)
        batch_op.create_index(batch_op.f('ix_pot_glaze_date'), ['glaze_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pot_glaze_fire_end'), ['glaze_fire_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_pot_glaze_fire_kiln'), ['glaze_fire_kiln'], unique=True)
        batch_op.create_index(batch_op.f('ix_pot_glaze_fire_open'), ['glaze_fire_open'], unique=False)
        batch_op.create_index(batch_op.f('ix_pot_glaze_fire_program_id'), ['glaze_fire_program_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pot_glaze_fire_start'), ['glaze_fire_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_pot_throw_date'), ['throw_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pot_throw_weight'), ['throw_weight'], unique=False)
        batch_op.create_index(batch_op.f('ix_pot_trim_date'), ['trim_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pot_trim_surface_treatment'), ['trim_surface_treatment'], unique=False)
        batch_op.create_index(batch_op.f('ix_pot_trim_weight'), ['trim_weight'], unique=False)

    op.create_table('program_segment',
    sa.Column('firing_program_id', sa.Integer(), nullable=True),
    sa.Column('firing_segment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firing_program_id'], ['firing_program.id'], name=op.f('fk_program_segment_firing_program_id_firing_program')),
    sa.ForeignKeyConstraint(['firing_segment_id'], ['firing_segment.id'], name=op.f('fk_program_segment_firing_segment_id_firing_segment'))
    )
    op.create_table('pot_glaze',
    sa.Column('pot_id', sa.Integer(), nullable=True),
    sa.Column('glaze_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['glaze_id'], ['glaze.id'], name=op.f('fk_pot_glaze_glaze_id_glaze')),
    sa.ForeignKeyConstraint(['pot_id'], ['pot.id'], name=op.f('fk_pot_glaze_pot_id_pot'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pot_glaze')
    op.drop_table('program_segment')
    with op.batch_alter_table('pot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pot_trim_weight'))
        batch_op.drop_index(batch_op.f('ix_pot_trim_surface_treatment'))
        batch_op.drop_index(batch_op.f('ix_pot_trim_date'))
        batch_op.drop_index(batch_op.f('ix_pot_throw_weight'))
        batch_op.drop_index(batch_op.f('ix_pot_throw_date'))
        batch_op.drop_index(batch_op.f('ix_pot_glaze_fire_start'))
        batch_op.drop_index(batch_op.f('ix_pot_glaze_fire_program_id'))
        batch_op.drop_index(batch_op.f('ix_pot_glaze_fire_open'))
        batch_op.drop_index(batch_op.f('ix_pot_glaze_fire_kiln'))
        batch_op.drop_index(batch_op.f('ix_pot_glaze_fire_end'))
        batch_op.drop_index(batch_op.f('ix_pot_glaze_date'))
        batch_op.drop_index(batch_op.f('ix_pot_clay_type'))
        batch_op.drop_index(batch_op.f('ix_pot_bisque_fire_start'))
        batch_op.drop_index(batch_op.f('ix_pot_bisque_fire_program_id'))
        batch_op.drop_index(batch_op.f('ix_pot_bisque_fire_kiln'))
        batch_op.drop_index(batch_op.f('ix_pot_author'))

    op.drop_table('pot')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('kiln', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiln_name'))
        batch_op.drop_index(batch_op.f('ix_kiln_brand'))

    op.drop_table('kiln')
    with op.batch_alter_table('glaze', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glaze_brand'))

    op.drop_table('glaze')
    op.drop_table('firing_segment')
    op.drop_table('firing_program')
    with op.batch_alter_table('clay', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clay_brand'))

    op.drop_table('clay')
    # ### end Alembic commands ###
