"""empty message

Revision ID: b6f9ee45445a
Revises: 220d38fbac34
Create Date: 2023-08-13 19:25:18.011277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f9ee45445a'
down_revision = '220d38fbac34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot_glaze', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_layers', sa.Integer(), nullable=True))
        batch_op.alter_column('pot_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('glaze_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pot_glaze', schema=None) as batch_op:
        batch_op.alter_column('glaze_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('pot_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('number_of_layers')

    # ### end Alembic commands ###
