"""empty message

Revision ID: e90df647d82c
Revises: 25c847a6b0de
Create Date: 2023-07-21 12:33:42.623928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90df647d82c'
down_revision = '25c847a6b0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firing_program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firing_program', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
